version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
    command: sh -c "cd /app; yarn start"
