version: '3'

services:
  jupyter:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./workspace:/workspace
    ports:
      - 8888:8888
    command: jupyter-lab --allow-root --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.token='' --notebook-dir=/workspace
