name: Github Pages
on:
  push:
    branches:
      - main
jobs:
  deploy-github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Build and deploy frontend
        run: |
          cd frontend/app
          npm install
          npm run build
          mv build ../../docs
          cd ../..
        env:
          CI: false
      - name: Auto commit Github Pages
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto deployment by Github Actions
          file_pattern: docs
          push_options: --force
